version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

